---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      serviceAccountName: regcred
      containers:
        - name: backend
          # Replace the `<>` placeholders with your docker registry info
          image: europe-west4-docker.pkg.dev/development-infratron/infratron/2048-game:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 1m
              memory: 1Mi
            limits:
              cpu: 300m
              memory: 200Mi
          # securityContext:
          #   readOnlyRootFilesystem: true
          #   runAsNonRoot: true
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #       - all
