apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: game-2048
spec:
  template:
    spec:
      containers:
        # Replace with your docker registry info
        - image: eu-docker.pkg.dev/infratron-development/sample-apps/2048-game:latest
          ports:
            - containerPort: 80
